import React from 'react'
import WorkTile from './WorkTile'
import WorkTileOut from './WorkTileOut'
import PlayTile from './PlayTile'
import PlayTileIn from './PlayTileIn'


class Work extends React.Component {
  render() {
    return (
    <section>
        <h1>Projects</h1>
        <WorkTile title='Mapping Emotion in 3D' info='Geospatial Application' summary='3D application using physiological data collected from cyclists to examine how emotions vary as a function of location, specifically through space and time.' img='images/preview/cyclestress.jpg' link='https://gcmillar.github.io/3D-Buildings-NL/'/>
        <WorkTile title='Spatial Decision Support Tool for Tangible Interaction' info='Geospatial Application' summary='Quantifies tangible interaction through processing, analyzing, and visualizing terrain form changes created from users’ manipulation of a tangible interface for geospatial modeling—Tangible Landscape.' img='images/preview/tansupport.jpg' link=''/>
        <WorkTile title='GAPS' info='Education & Outreach' summary='GAPS (Geospatial Applications for Problem Solving) is designed to introduce high school students to geospatial science, GIS, and advanced geovisualization technologies through an intensive after-school STEM learning experience.' img='images/preview/gaps.jpg' link='https://gaps.cnr.ncsu.edu/'/>
        <h1>Publications</h1>
        <WorkTileOut title='Tangible Landscape: A Hands-on Method for Teaching Terrain Analysis' info='*Millar G., Tabrizian P., Petrasova A., Petras V., Harmon B., Mitasova H., Meetenmeyer R.' summary=' This paper presents novel and effective methods for teaching about topography--or shape of terrain--and assessing 3-dimensional spatial learning using tangibles. We used Tangible Landscape--a tangible interface for geospatial modeling--to teach multiple hands-on tangible lessons on the concepts of grading, geomorphology, and hydrology. We examined students ratings of the systems usability and user experience and tested students acquisition and transfer of knowledge. Our results suggest the physicality of the objects enabled the participants to effectively interact with the system and each other, positively impacting ratings of usability and task-specific knowledge building. These findings can potentially advance the design and implementation of tangible teaching methods for the topics of geography, design, architecture, and engineering.' img='images/preview/chi.png' link='https://www.researchgate.net/profile/Brendan_Harmon2/publication/322355724_Tangible_Landscape_A_Hands-on_Method_for_Teaching_Terrain_Analysis/links/5a753deb45851541ce566c0c/Tangible-Landscape-A-Hands-on-Method-for-Teaching-Terrain-Analysis.pdf'/>
        <WorkTileOut title='Creating Content Guidelines for Consistent Display of Information on an Ecommerce Website' info='Pryor, M., *Millar, G.C., McNamara, A., Kaufman, L., & McLaughlin, A.C. ' summary='As part of a project in collaboration with Lenovoâs Global UX team, we analyzed a website using heuristic analysis, a cognitive walkthrough, and feedback from users through verbal protocols. With this information, we created a prototype version of proposed content guidelines. These guidelines aim to improve consistency on the website, which allowed users to quickly compare multiple laptops as well as make connections between the laptop hardware and typical uses. In this paper, we describe our process behind developing these guidelines and the resulting guidelines themselves to show how researchers may develop their own guidelines.' img='images/preview/hfes.jpg' link='http://journals.sagepub.com/doi/pdf/10.1177/1541931213601939' />
        <h1>Books</h1>
        <WorkTileOut title='Using data visualizations to foster emotion regulation during self-regulated learning with advanced learning technologies' info='Azevedo, R., Taub, M., Mudrick, N. V., *Millar, G. C., Bradbury, A. E., & Price, M. J.' summary=' Emotions play a critical role during learning and problem solving with advanced learning technologies. However, learners typically do not accurately monitor and regulate their emotions and may therefore not learn as much, disengage from the task, and not optimize their learning of the instructional material. We present a theoretically-based and empirically-driven conceptual framework that addresses emotion regulation by proposing the use of visualizations of oneâs and othersâ CAMM-SRL multichannel data to facilitate learnersâ monitoring and regulation of their emotions during learning with advanced learning technologies. We conclude with future directions that can lead to a systematic interdisciplinary research agenda that addresses outstanding emotion regulation-related issues by integrating models, theories, methods, and analytical techniques for the areas of cognitive, learning, and affective sciences, human computer interaction, data visualization, big data, data mining, data science, learning analytics, open learner models, and SRL.' img='images/preview/ieee.jpeg' link='https://link.springer.com/chapter/10.1007/978-3-319-64274-1_10' />
        <h1>Presentations</h1>
        <WorkTileOut title='Increasing Underrepresented High School Students STEM Career Awareness and Interest: An Informal Geospatial Science Program.' info='*Millar, G. C., Money, E. S., Bunds, K. S., Mitasova, H.' summary=' ' img='images/preview/agu.png' link='https://gcmillar.github.io/presentations/agu2018#/' />
        <WorkTileOut title='Hands-on Methods for Teaching Landscape Form and Processes.' info='*Millar G. C., Tabrizian P., Petrasova A., Petras V., Harmon B., Mitasova H., Meetenmeyer R. 2018.' summary=' ' img='images/preview/iale.png' link='https://gcmillar.github.io/presentations/us_iale2018#' />
    </section>
    )
  }
}
export default Work
